### ISSUE TITLE
models/backends not found error

### ISSUE THREAD

**Issue by Jojo-00** [INM-6/NetworkUnit#20]
I installed networkunit with pip and tried to import the modules in my python-script. When I try to start the program the following error message occurs:

Traceback (most recent call last):
  File ".\nu_test.py", line 3, in <module>
    from networkunit import tests, scores, models
  File "C:\Users\Admin\anaconda3\lib\site-packages\networkunit\__init__.py", line 9, in <module>        
    from . import tests, models, capabilities, scores, plots
  File "C:\Users\Admin\anaconda3\lib\site-packages\networkunit\models\__init__.py", line 17, in <module>
    exec("from {} import {}".format(modname, module_name))
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\anaconda3\lib\site-packages\networkunit\models\model_loaded_data.py", line 2, in <module>
    from .backends import available_backends
ModuleNotFoundError: No module named 'networkunit.models.backends'

**Comment by mdenker** [comment]
Sorry for the late reply, this issue slipped our attention. Thank you for reporting this bug.

Indeed, the `backend` folder was missing from the `setup.py` script, such that the pip-installed version led to the import error. Should be fixed by #21 and we will create a hotfix release 0.1.2 shortly.

As a fast workaround, cloning the library without installing via pip should work.

**Comment by mdenker** [comment]
The release 0.1.2, available from pypi using `pip install --upgrade networkunit` should fix this issue.

**Comment by Jojo-00** [comment]
Thank you for the quick bug-fix. The installation with pip has now worked.
